### ISSUE TITLE
Breaking this library into subcomponents or not?

### ISSUE THREAD

**Issue by chenglou** [chenglou/data-structures#2]
Will leave this issue open for library users.

**Comment by Anachron** [comment]
Hi there and thank you for making chenglou.
I think it's small as it is, so no need to break it into several subcomponents.

**Comment by chenglou** [comment]
Yeah... I imagine there are already projects dependent on this, so I guess there's no need to break compatibility just to follow some community wisdom about modularization. Thanks for the feedback!
