### ISSUE TITLE
Full rewrite in JS or not?

### ISSUE THREAD

**Issue by chenglou** [chenglou/data-structures#5]
Kind of a sensational title, since it'd mostly just be taking the compiled js and format it a bit. But this might help adoption.

**Comment by mcharytoniuk** [comment]
I am into it and I actually might participate in rewriting it.

**Comment by chenglou** [comment]
I might have exaggerated the task though, the transpiled js is already there so it shouldn't take too long to clean it up. CoffeeScript has been extremely fun, but I want to spread this to more people.

What do you think of breaking this library apart into unitary data structures? I kind of like the unified documentation but maybe including the whole library is a bit too much of a commitment for some. Especially at the front-end.

**Comment by mcharytoniuk** [comment]
I think better not. These utilities are strongly coupled together. For example if you would like to introduce inheritance like this you would have serious problems with several repositories:

Set < Queue < PriorityQueue

**Comment by chenglou** [comment]
Can't I just `require()` the class in question? Unless there's something I've missed.
But say it is less well coupled this way for some reason, there's surprisingly little reuse currently in the repo, simply because, say, constructing a queue from a linked list is super slow (btw, heap is a priority queue already). And since it's already mature, I'm not sure how much inheritance there is in the future.

**Comment by mcharytoniuk** [comment]
I need to make some backward incompatible changes so I am going to maintain a fork. I have converted Trie and Map to plain JavaScript and pruned them from some coffescript-specific variables.  If you still want to rewrite them it should be possible to cherry-pick something.

I hope this helps.

**Comment by chenglou** [comment]
Thanks. Mind showing them?

**Comment by mcharytoniuk** [comment]
Here is the initial commit:
https://github.com/benderjs/data-container/tree/fca0d8b598513491e1bdc07a09a1c21b473b6a58/libraries/scripts/Bender/DataContainer

**Comment by chenglou** [comment]
Well this has been sitting here long enough. I guess quite a few people are using this in production so no reason to make a rewrite for the sake of. Closing!
